### ISSUE TITLE
Hover over period changes positioning (causes flickering)

### ISSUE THREAD

**Issue by craftbyte** [UL-FRI/urnik#38]
When hovering over a title of a time period some text shifts locations.
In certain occasions, this causes the title to move and start flickering.

![image](https://user-images.githubusercontent.com/3154203/67089471-f4c69c00-f1a7-11e9-96be-e2de9359b985.png)
![image](https://user-images.githubusercontent.com/3154203/67089518-19227880-f1a8-11e9-81a9-fb02feaf7851.png)

**Comment by UrbanKocmut** [comment]
Could you provide a link that displays this behavior?

**Comment by craftbyte** [comment]
https://urnik.fri.uni-lj.si/timetable/fri-2019_2020-zimski-1-1/allocations?classroom=123

RA_LV on Friday
Also, this seems to only happen in Chrome

**Comment by zznidar** [comment]
Apparently Chrome treats "auto" differently than other browsers. When additional info pops up, there's less space remaining, thus it re-positions the elements. 

Positioning the text to center manually instead of relying on auto seems to solve the problem (see #40).
